export const MAKE_REQUEST = "MAKE_REQUEST";
export const FAIL_REQUEST = "FAIL_REQUEST";
export const RESET_STATE = "RESET_STATE";

//DEVICE
export const SET_DEVICE_LIST = "SET_DEVICE_LIST";
export const ADD_STATUS = "ADD_STATUS";
export const DELETE_STATUS = "DELETE_STATUS";
export const GET_STATUS_OBJ = "GET_STATUS_OBJ";
export const UPDATE_STATUS = "UPDATE_STATUS";
export const SUBMIT_STATUS = "SUBMIT_STATUS";
export const VERIFYING_STATUS = "VERIFYING_STATUS";
export const VERIFIED_STATUS = "VERIFIED_STATUS";
export const RETURN_STATUS = "RETURN_STATUS";
export const RENEW_STATUS = "RENEW_STATUS";
export const SF_02 = "SF_02";
export const DOWLOAD_SF_02 = "DOWLOAD_SF_02";
export const SET_CURRENT_ASSIGNED_FILTER = "SET_CURRENT_ASSIGNED_FILTER";
export const SET_CURRENT_UNASSIGNED_FILTER = "SET_CURRENT_UNASSIGNED_FILTER";
export const SET_DEVICE_FILTER_LIST = "SET_DEVICE_FILTER_LIST";
export const SET_DEVICE_MASTER_LOOKUP = "SET_DEVICE_MASTER_LOOKUP";
export const SET_DEVICE_DASHBOARD = "SET_DEVICE_DASHBOARD";
export const SET_DEVICE_ASSIGNED = "SET_DEVICE_ASSIGNED";
export const SET_DEVICE_UNASSIGNED = "SET_DEVICE_UNASSIGNED";
export const COUNT = "COUNT";
//for login reducer
export const SET_USER_DETAIL = "SET_USER_DETAIL";
//Dropdrow
export const GET_DROPDROW_LIST = "GET_DROPDROW_LIST";
export const GET_PROVINCE_LIST = "GET_PROVINCE_LIST";
export const GET_COUNTRY_LIST = "GET_COUNTRY_LIST";
export const GET_COUNTRY_LIST_ADD = "GET_COUNTRY_LIST_ADD";
export const GET_POSTCODE_LIST = "GET_POSTCODE_LIST";
export const SET_DISTRICT_LIST = "SET_DISTRICT_LIST";
export const SET_SUB_DISTRICT_LIST = "SET_SUB_DISTRICT_LIST";

//Menu
export const SET_MENU_LIST = "SET_MENU_LIST";
export const SET_CURRENT_UGT_GROUP = "SET_CURRENT_UGT_GROUP";
export const SET_SUB_MENU_LIST = "SET_SUB_MENU_LIST";
export const SET_SUB_MENU_DEVICE_LIST = "SET_SUB_MENU_DEVICE_LIST";
export const SET_SUB_MENU_SUBSCRIBER_LIST = "SET_SUB_MENU_SUBSCRIBER_LIST";
export const SET_SELECTED_SUB_MENU = "SET_SELECTED_SUB_MENU";
export const SET_SUB_MENU_EAC_TRACKING_LIST = "SET_SUB_MENU_EAC_TRACKING_LIST";
// export const SET_SELECTED_YEAR = "SET_SELECTED_YEAR";
// export const SET_SELECTED_MONTH = "SET_SELECTED_MONTH";
export const SET_EAC_SELECTED_YEAR = "SET_EAC_SELECTED_YEAR";
export const SET_EAC_SELECTED_MONTH = "SET_EAC_SELECTED_MONTH";
export const SET_OPEN_MENU = "SET_OPEN_MENU";

//Modal
export const SET_OPEN_MODAL = "SET_OPEN_MODAL";
export const SET_CLOSE_MODAL = "SET_CLOSE_MODAL";

export const CLEAR_MODAL = "CLEAR_MODAL";
export const SET_OPEN_FAIL_MODAL = "SET_OPEN_FAIL_MODAL";

//Subscriber
export const GET_SUBSCRIBER_DASHBOARD_OBJ = "GET_SUBSCRIBER_DASHBOARD_OBJ";
export const GET_SUBSCRIBER_ASSIGN_OBJ = "GET_SUBSCRIBER_ASSIGN_OBJ";
export const GET_SUBSCRIBER_UNASSIGN_OBJ = "GET_SUBSCRIBER_UNASSIGN_OBJ";
export const GET_SUBSCRIBER_FILTER_LIST = "GET_SUBSCRIBER_FILTER_LIST";
export const GET_SUBSCRIBER_INFO = "GET_SUBSCRIBER_INFO";
export const CREATE_SUBSCRIBER_STATUS = "ADD_SUBSCRIBER";
export const CREATE_AGGREGATE_SUBSCRIBER_STATUS = "ADD_AGGREGATE";
export const GET_SUB_DISTRICTBENE_LIST = "GET_SUB_DISTRICTBENE_LIST";
export const GET_SUB_DISTRICTBENE_LIST_ALL = "GET_SUB_DISTRICTBENE_LIST_ALL";
export const GET_DISTRICTBENE_LIST = "GET_DISTRICTBENE_LIST";
export const GET_POSTCODEBENE_LIST = "GET_POSTCODEBENE_LIST";
export const GET_PROVINCEBENE_LIST = "GET_PROVINCEBENE_LIST";
export const GET_DISTRICTBENE_LIST_ADD = "GET_DISTRICTBENE_LIST_ADD";
export const GET_POSTCODEBENE_LIST_ADD = "GET_POSTCODEBENE_LIST_ADD";
export const GET_PROVINCEBENE_LIST_ADD = "GET_PROVINCEBENE_LIST_ADD";
export const GET_SUB_DISTRICTBENE_LIST_ADD = "GET_SUB_DISTRICTBENE_LIST_ADD";
export const GET_DISTRICTBENE_LIST_EDIT = "GET_DISTRICTBENE_LIST_EDIT";
export const GET_POSTCODEBENE_LIST_EDIT = "GET_POSTCODEBENE_LIST_EDIT";
export const GET_PROVINCEBENE_LIST_EDIT = "GET_PROVINCEBENE_LIST_EDIT";
export const GET_SUB_DISTRICTBENE_LIST_EDIT = "GET_SUB_DISTRICTBENE_LIST_EDIT";
export const GET_HISTORY_LOG_ACTIVE = "GET_HISTORY_LOG_ACTIVE";
export const GET_HISTORY_LOG_INACTIVE = "GET_HISTORY_LOG_INACTIVE";
export const GTE_BINARY_FILE_HISTORY = "GET_BINARY_FILE_HISTORY";
export const EDIT_AGGREGATE_STATUS = "EDIT_AGGREGATE_STATUS";
export const EDIT_SUBSCRIBER_STATUS = "EDIT_SUBSCRIBER_STATUS";
export const WITHDRAWN_SUBSCRIBER_STATUS = "WITHDRAWN_SUBSCRIBER_STATUS"
export const RENEW_AGGREGATE_STATUS = "RENEW_AGGREGATE_STATUS";
export const RENEW_SUBSCRIBER_STATUS = "RENEW_SUBSCRIBER_STATUS";
export const GET_RENEW_SUBSCRIBER_INFO = "GET_RENEW_SUBSCRIBER_INFO";
export const GET_RENEW_EDIT_SUBSCRIBER_INFO = "GET_RENEW_EDIT_SUBSCRIBER_INFO";
//Portfolio
export const GET_PORTFOLIO_DASHBOARD_OBJ = "GET_PORTFOLIO_DASHBOARD_OBJ";
export const GET_PORTFOLIO_DASHBOARD_LIST_OBJ =
  "GET_PORTFOLIO_DASHBOARD_LIST_OBJ";
export const GET_PORTFOLIO_DEVICE_OBJ = "GET_PORTFOLIO_DEVICE_OBJ";
export const GET_PORTFOLIO_SUBSCRIBER_OBJ = "GET_PORTFOLIO_SUBSCRIBER_OBJ";

export const GET_MECHANISM_LIST_OBJ = "GET_MECHANISM_LIST_OBJ";
export const CREATE_PORTFOLIO_STATUS = "ADD_PORTFOLIO";
export const GET_PORTFOLIO_INFO = "GET_PORTFOLIO_INFO";
export const GET_PORTFOLIO_DETAIL = "GET_PORTFOLIO_DETAIL";
export const DELETE_PORTFOLIO_STATUS = "DELETE_PORTFOLIO";
export const EDIT_PORTFOLIO_STATUS = "EDIT_PORTFOLIO_STATUS";
export const EDIT_PORTFOLIO_SUBSCRIBER_STATUS =
  "EDIT_PORTFOLIO_SUBSCRIBER_STATUS";
export const EDIT_PORTFOLIO_DEVICE_STATUS = "EDIT_PORTFOLIO_DEVICE_STATUS";

//EAC
export const GET_EAC_PORTFOLIO_YEAR_LIST = "GET_EAC_PORTFOLIO_YEAR_LIST";
export const GET_EAC_PORTFOLIO_MONTH_LIST = "GET_EAC_PORTFOLIO_MONTH_LIST";

//EAC-Transfer
export const GET_EAC_TRANSFER_REQ_LIST = "GET_EAC_TRANSFER_REQ_LIST";
export const GET_EAC_TRANSFER_REQ_INFO = "GET_EAC_TRANSFER_REQ_INFO";
export const GET_EAC_TRANSFER_REQ_PORT_YEAR_LIST =
  "GET_EAC_TRANSFER_REQ_PORT_YEAR_LIST";
export const GET_EAC_TRANSFER_REQ_PORT_MONTH_LIST =
  "GET_EAC_TRANSFER_REQ_PORT_MONTH_LIST";
export const GET_EAC_TRANSFER_REQUEST_LIST = "GET_EAC_TRANSFER_REQUEST_LIST";
export const GET_EAC_TRANSFER_REQUEST_INFO = "GET_EAC_TRANSFER_REQUEST_INFO";
export const CREATE_RESERVATION = "CREATE_RESERVATION";

//EAC-Redemption
export const GET_EAC_REDEMPTION_REQUEST_LIST =
  "GET_EAC_REDEMPTION_REQUEST_LIST";
export const GET_EAC_REDEMPTION_REQUEST_INFO =
  "GET_EAC_REDEMPTION_REQUEST_INFO";
export const GET_EAC_REDEMPTION_SUBSCRIBER_LIST =
  "GET_EAC_REDEMPTION_SUBSCRIBER_LIST";

//Settlement
export const GET_PORTFOLIO_YEAR_LIST = "GET_PORTFOLIO_YEAR_LIST";
export const GET_PORTFOLIO_MONTH_LIST = "GET_PORTFOLIO_MONTH_LIST";
export const GET_SETTLEMENT_OVERVIEW = "GET_SETTLEMENT_OVERVIEW";
export const GET_SETTLEMENT_OVERVIEW_SUMMARY =
  "GET_SETTLEMENT_OVERVIEW_SUMMARY";
export const GET_SETTLEMENT_MONTHLY_SUMMARY = "GET_SETTLEMENT_MONTHLY_SUMMARY";
export const GET_SETTLEMENT_MONTHLY_GENERATION =
  "GET_SETTLEMENT_MONTHLY_GENERATION";
export const GET_SETTLEMENT_MONTHLY_CONSUMPTION =
  "GET_SETTLEMENT_MONTHLY_CONSUMPTION";
export const GET_INVENTORY_SUPPLY_USAGE_LIST =
  "GET_INVENTORY_SUPPLY_USAGE_LIST";
export const GET_REMAIN_ENERGY_ATTRIBUTE_LIST =
  "GET_REMAIN_ENERGY_ATTRIBUTE_LIST";
export const GET_SETTLEMENT_MONTHLY_DETAIL = "GET_SETTLEMENT_MONTHLY_DETAIL";
export const SETTLEMENT_APPROVAL = "SETTLEMENT_APPROVAL";
export const GET_SETTLEMENT_APPROVAL = "GET_SETTLEMENT_APPROVAL";
export const SET_SELECTED_YEAR = "SET_SELECTED_YEAR";
export const SET_SELECTED_MONTH = "SET_SELECTED_MONTH";
